// examples/web-angular-example/src/main.ts
import { Component, signal, type OnInit } from "@angular/core";
import { bootstrapApplication } from "@angular/platform-browser";
import {
  createWeChatAuth,
  type WeChatAuthorizeResult,
  type WeChatSignInResult,
} from "@chinafast/web-wechat-auth";

const redirectUri = "http://localhost:4200/";
const client = createWeChatAuth({
  web: { appId: "wx_your_open_platform_website_app_id", redirectUri },
  officialAccount: { appId: "wx_your_official_account_app_id", redirectUri },
  stateUrl: "http://localhost:4105/auth/wechat/state",
  exchangeUrl: "http://localhost:4105/auth/wechat",
});

@Component({
  selector: "app-root",
  standalone: true,
  template: `<main>
    <h1>Angular + WeChat</h1>
    <p>Standalone component using Angular signals.</p>
    <p>The included Express server validates state and exchanges the code.</p>
    <button [disabled]="loading()" (click)="signIn()">
      {{ loading() ? "Opening WeChat…" : "Continue with WeChat" }}
    </button>
    @if (result()) {
      <pre>{{ json() }}</pre>
    }
  </main>`,
})
class AppComponent implements OnInit {
  readonly loading = signal(false);
  readonly result = signal<WeChatAuthorizeResult | WeChatSignInResult | null>(null);
  json = () => JSON.stringify(this.result(), null, 2);
  async signIn() {
    this.loading.set(true);
    this.result.set(await client.signIn());
    this.loading.set(false);
  }
  async ngOnInit() {
    if (["code", "error", "errcode"].some((key) => new URL(location.href).searchParams.has(key))) {
      this.result.set(await client.handleRedirectCallback(location.href));
    }
  }
}

bootstrapApplication(AppComponent).catch(console.error);

// examples/web-react-example/src.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { createWeChatAuth } from "@chinafast/web-wechat-auth";
import {
  WeChatAuthProvider,
  useWeChatAuth,
  useWeChatRedirectCallback,
} from "@chinafast/web-wechat-auth/react";
// oxlint-disable-next-line import/no-unassigned-import -- Vite applies global CSS via import.
import "./style.css";

const client = createWeChatAuth({
  web: {
    appId: import.meta.env.VITE_WECHAT_WEB_APP_ID || "",
    redirectUri: import.meta.env.VITE_WECHAT_REDIRECT_URI || window.location.origin + "/",
  },
  officialAccount: {
    appId: import.meta.env.VITE_WECHAT_OFFICIAL_ACCOUNT_APP_ID || "",
    redirectUri: import.meta.env.VITE_WECHAT_REDIRECT_URI || window.location.origin + "/",
  },
  stateUrl: "http://localhost:4101/auth/wechat/state",
  exchangeUrl: "http://localhost:4101/auth/wechat",
});

function SignIn() {
  const { signIn, loading, error, environment } = useWeChatAuth();
  const callback = useWeChatRedirectCallback();
  return (
    <main>
      <h1>React + WeChat</h1>
      <p>
        Detected: {environment.device} / {environment.browser}
      </p>
      <p>The included Express server validates state and exchanges the code.</p>
      <button disabled={loading} onClick={() => void signIn()}>
        {loading ? "Opening WeChat…" : "Continue with WeChat"}
      </button>
      {error && <p className="error">{error.message}</p>}
      {callback && <pre>{JSON.stringify(callback, null, 2)}</pre>}
    </main>
  );
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <WeChatAuthProvider client={client}>
      <SignIn />
    </WeChatAuthProvider>
  </StrictMode>
);
